### ISSUE TITLE
Website administrator

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/My-First-Agile-Project#5]
In order to **meet the needs of owner and customers** in my role as **website administrator** I can **organise the tasks needed with my team to reach our goals**

## Tasks
- [ ] Design feedback form and include relevant criteria
- [ ] Design pool to be added to website, discuss relevant information with owner/customer
- [ ] Ask customer for any possible additions to the website
